/**
 * Machine-readable error codes.
 *
 * Defined as an `as const` object (instead of a TypeScript `enum`) so the
 * syntax is fully erasable and produces no extra runtime constructs.
 */
export const ErrorCode = {
  CORS_UNALLOWED: "CORS_UNALLOWED",

  // Auth Middleware
  MISSING_TOKEN: "MISSING_TOKEN",
  UNAUTHORIZED: "UNAUTHORIZED",

  // Auth — Registration / Login
  MISSING_PARAMETERS: "MISSING_PARAMETERS",
  MISSING_CREDENTIALS: "MISSING_CREDENTIALS",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  MISSING_EMAIL: "MISSING_EMAIL",
  EMAIL_TAKEN: "EMAIL_TAKEN",
  USERNAME_TAKEN: "USERNAME_TAKEN",
  INVALID_LOGIN: "INVALID_LOGIN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  ACCOUNT_DEACTIVATED: "ACCOUNT_DEACTIVATED",

  // User
  USER_NOT_FOUND: "USER_NOT_FOUND",
  MISSING_NEW_USERNAME: "MISSING_NEW_USERNAME",
  USERNAME_TOO_SHORT: "USERNAME_TOO_SHORT",
  MISSING_PASSWORD_FIELDS: "MISSING_PASSWORD_FIELDS",
  PASSWORD_TOO_SHORT: "PASSWORD_TOO_SHORT",
  PASSWORD_WRONG: "PASSWORD_WRONG",
  PASSWORD_SAME: "PASSWORD_SAME",

  // General
  NOT_FOUND: "NOT_FOUND",
  NOT_IMPLEMENTED: "NOT_IMPLEMENTED",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  REQUEST_TIMEOUT: "REQUEST_TIMEOUT",
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];
